// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgtbayltqvrxxebjwqty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBndGJheWx0cXZyeHhlYmp3cXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzE0ODYsImV4cCI6MjA2MDQwNzQ4Nn0.231_-tLjSHcPq2d2BJjfsVmfGM2oMObyTMmXxFuv_k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);